{% set name = "Bonsu" %}
{% set version = "3.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 8a6287c6066416d6c012a0ddd5142de304fe60a3dc9da1417ada1f2ccf63ebd7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv --global-option=build_ext --global-option=-I$PREFIX/include
  entry_points:
    - bonsu = bonsu.interface.bonsu:main

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - {{ cdt('libXxf86vm') }}  # [linux]
    - {{ cdt('mesa-libgl') }}  # [linux]
  host:
    - pip
    - setuptools
    - python
    - pillow
    - wxpython
    - vtk
    - hdf5
    - h5py
    - fftw
    - cython
  run:
    - python
    - pillow
    - wxpython
    - vtk
    - hdf5
    - h5py
    - numpy
    - fftw
    - cython

test:
  imports:
    - bonsu
    - bonsu.docs
    - bonsu.image
    - bonsu.interface
    - bonsu.lib
    - bonsu.operations
    - bonsu.phasing
    - bonsu.sequences
  requires:   # [not win]
    - pip        # [not win]
  commands:   # [not win]
    - pip check  # [not win]

about:
  home: https://github.com/bonsudev/bonsu
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: bonsu/licence/gpl.txt
  summary: Bonsu - The Interactive Phase Retrieval Suite

extra:
  recipe-maintainers:
    - ndevenish
